# GENERATED by ggen from typer-pack/ontology.ttl. Do not hand-edit.
from __future__ import annotations

import typer

app = typer.Typer(
    name="ggen-typer",
    help="Ontology-generated Typer commands.",
    no_args_is_help=True,
)


@app.callback()
def root() -> None:
    """Keep ontology commands as explicit subcommands, including one-command apps."""


@app.command("greet")
def greet(
    name: str = typer.Argument(..., help="Subject to greet."),
) -> None:
    """Greet a named subject."""
    typer.echo("Hello, {name}!".format(name=name))


if __name__ == "__main__":
    app()
