# GENERATED by ggen from fastmcp-pack/ontology.ttl. Do not hand-edit.
from __future__ import annotations

from fastmcp import FastMCP

mcp = FastMCP("ggen-fastmcp")


@mcp.tool(name="greet", description="Return a deterministic greeting without external actuation.")
def greet(name: str) -> str:
    """Return a deterministic greeting without external actuation.

    Args:
        name: Subject to greet.
    """
    return "Hello, {name}!".format(name=name)


if __name__ == "__main__":
    mcp.run()
